config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check
  root "photos#feed"
  # get "/authenticate/login", to: "authentication#login"
  # get "/authenticate/signup", to: "authentication#signup"
  # get "/feed/album", to: "feed#album"
  # get "/discover/photo", to: "discover#photo"
  # get "/discover/album", to: "discover#album"
  # get "/articles", to: "articles#index"
  # put "/discover/follow", to: "discover#follow", as: :follow
  # get "/personal_info/photo/:id", to: "personal_info#photo", as: :personal_info_photo
  # get "/personal_info/album/:id", to: "personal_info#album", as: :personal_info_album
  # get "/personal_info/following/:id", to: "personal_info#following", as: :personal_info_following
  # get "/personal_info/follower/:id", to: "personal_info#follower", as: :personal_info_follower
  # get "/users/edit/:id", to: "users#edit", as: :edit_user
  #patch "/users/update/:id", to: "users#update", as: :update_user
  devise_scope :user do
    put "/users/update/:id", to: "devise/registrations#update_name", as: :update_user
  end
  # get "/users", to: "users#index", as: :users
  # delete "/users/delete/:user_id", to: "users#destroy", as: :delete_user
  # # post "/react_photo", to: "react_photos#create"
  # # delete "/react_photo", to: "react_photos#destroy"
  # # post "/react_album", to: "react_albums#create"
  # # delete "/react_album", to: "react_albums#destroy"
  # put "/react_photos", to: "react_photos#handle_like", as: :react_photo
  # put "/react_albums", to: "react_albums#handle_like", as: :react_album
  # scope module: 'users' do
  #   resources :photos, :albums
  # end

  
  # scope module: 'users' do
  #   resources :photos, :albums
  # end
  resources :users
  get "/users/:user_id/followings", to: "follows#followings", as: :followings
  get "/users/:user_id/followers", to: "follows#followers", as: :followers
  post "/follow", to: "follows#create", as: :follow_user
  delete "/unfollow", to: "follows#destroy", as: :unfollow_user
  get "/photos/discover", to: "photos#discover", as: :discover_photo
  get "/photos/feed", to: "photos#feed", as: :feed_photo
  get "/albums/discover", to: "albums#discover", as: :discover_album
  get "/albums/feed", to: "albums#feed", as: :feed_album
  get "/follow_button/user/:user_id", to: "follows#follow_button", as: :follow_button
  get "/unfollow_button/user/:user_id", to: "follows#unfollow_button", as: :unfollow_button

  post "/react_photos", to: "react_photos#create", as: :react_photo
  delete "/unreact_photos", to: "react_photos#destroy", as: :unreact_photo
  get "/react_photo_button/photo/:photo_id", to: "react_photos#react_button", as: :react_photo_button
  get "/unreact_photo_button/photo/:photo_id", to: "react_photos#unreact_button", as: :unreact_photo_button

  post "/react_albums", to: "react_albums#create", as: :react_album
  delete "/unreact_albums", to: "react_albums#destroy", as: :unreact_album
  get "/react_album_button/album/:album_id", to: "react_albums#react_button", as: :react_album_button
  get "/unreact_album_button/album/:album_id", to: "react_albums#unreact_button", as: :unreact_album_button

 
  

  # refactoring code
  resources :users, shallow: true do
    resources :photos, :albums
  end

  # routes for admin
  get "/admin/manage_users", to: "admins#manage_users", as: :manage_users
  get "/admin/manage_photos", to: "admins#manage_photos", as: :manage_photos
  get "/admin/manage_albums", to: "admins#manage_albums", as: :manage_albums
  get "/admin/edit_user/:id", to: "admins#edit_user", as: :admin_edit_user
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/admins/_album_card.html.erb
<% ele = local_assigns[:ele] %>
<% @list_photos = ele.photos %>
<div class=" d-flex flex-row justify-content-center ">
    <div class="img-item p-4">
        <div class="contain-rotate-img">
            <% if @list_photos.empty? %>
                <img src="" alt="">
            <% else %>
                <% @list_photos.each_with_index do |photo,index| %>
                        <%= render '/shared/display_image', ele:photo.image %>
                <% end %>
            <% end %>
        </div>
        <div class="img-title d-flex justify-content-between">
            <div class="img-title-text" > 
                <p><%=ele.title%> </p>
            </div>
            <%= button_to edit_album_path(ele.id), method: :get, class: "edit-btn" do %>
                <div class="d-inline-block"><i class="fa-solid fa-pen-to-square"></i></div>
            <% end %>
            
        </div>
    </div>
</div>

app/views/admins/_photo_card.html.erb
<% ele = local_assigns[:ele] %>
<div class=" d-flex flex-row justify-content-center ">
    <div class="img-item">
        <%=render '/shared/display_image', ele: ele.image%>
        <div class="img-title d-flex justify-content-between">
            <div class="img-title-text" > 
                <p><%=ele.title%> </p>
            </div>
            <%= button_to edit_photo_path(ele.id), method: :get, class: "edit-btn" do %>
                <div class="d-inline-block"><i class="fa-solid fa-pen-to-square"></i></div>
            <% end %>
            
        </div>
    </div>
</div>

app/views/admins/edit_user.html.erb
<%session[:success_redirect]=manage_users_path%>
<%session[:failure_redirect]=admin_edit_user_path(@resource)%>
<div class="row h-100 edit-user">
  <div class="col-0 col-lg-2 d-none d-lg-flex flex-row justify-content-center mt-4">
      <ul class="d-inline-block nav-list" >
          <a href="#">
                <li class="d-block mb-2">Manage Photos</li>
            </a>
            <a href="/discover/photo">
                <li class="d-block mb-2">Manage Albums</li>
            </a>
            <a href="/discover/photo">
                <li class="d-block mb-2">Manage Users</li>
            </a>
      </ul>
  </div>
  <div class="col-12 col-lg-8 center-container d-flex flex-column align-items-center "> 
      <div class="header w-100 d-flex flex-row justify-content-between">
            <p>Edit User Profile</p>
            <%=button_to  users_path, class: "back-btn"  do%>
                <p class="m-0">Back</p>
            <%end%>
                
      </div>
      <%= form_with(model: @resource, html: { method: :put, class:"w-100" }, url: update_user_path(@resource)) do |f| %>
        
        <div class="row ">
          <div class="col-5 d-flex flex-row justify-content-end align-items-center" >
          </div>
          <div class="col-5 d-flex flex-column align-items-start ">
            <div class="avt-edit-box mt-3"> 
                
                <div class="change-avt-btn"> 
                  <span>Change</span>
                  <%= f.file_field :profileImg, class: "form-control browse-btn", id: "photoInput" %>
                </div>
                <%= render '/shared/display_image', ele: f.object.profileImg%>
      
            </div>
            
            <p class="update-title update-title-box"> Basic information </p>
          </div>
        </div>
        <div class="row m-0 mt-2 ">
          <div class="col-5 d-flex flex-row justify-content-end align-items-center" >
            <%= f.label :firstName , "First Name" %><br />
          </div>
          <div class="col-5 d-flex flex-row justify-content-start ">
            <%= f.text_field :firstName, autofocus: true, class: "form-control  " %>
          </div>
        </div>
        <% if @resource.errors.has_key?(:firstName) %>
          <div class="row m-0 mt-2 ">
            <div class="col-5 d-flex flex-row justify-content-end align-items-center" >
            </div>
            <div class="col-5 d-flex flex-row justify-content-start error-message">
              <p><%= @resource.errors[:firstName].first%></p>
            </div>
          </div>
        <% end %>
        <div class="row m-0 mt-2 ">
          <div class="col-5 d-flex flex-row justify-content-end align-items-center">
            <%= f.label :lastName, "Last Name" %><br />
          </div>
          <div class="col-5 d-flex flex-row justify-content-start ">
            <%= f.text_field :lastName , class: "form-control  " %>
          </div>
        </div>
        <% if @resource.errors.has_key?(:lastName) %>
          <div class="row m-0 mt-2 ">
            <div class="col-5 d-flex flex-row justify-content-end align-items-center" >
            </div>
            <div class="col-5 d-flex flex-row justify-content-start error-message">
              <p><%= @resource.errors[:lastName].first%></p>
            </div>
          </div>
        <% end %>
        <div class="row m-0 mt-2 ">
          <div class="col-5 d-flex flex-row justify-content-end align-items-center">
            <%= f.label :email, "Email" %><br />
          </div>
          <div class="col-5 d-flex flex-row justify-content-start ">
            <%= f.email_field :email,  autocomplete: "email", class: "form-control  " %>
          </div>
        </div>
        <% if @resource.errors.has_key?(:email) %>
          <div class="row m-0 mt-2 ">
            <div class="col-5 d-flex flex-row justify-content-end align-items-center" >
            </div>
            <div class="col-5 d-flex flex-row justify-content-start error-message">
              <p><%= @resource.errors[:email].first%></p>
            </div>
          </div>
        <% end %>
        <div class="row m-0 mt-2 ">
          <div class="col-5 d-flex flex-row justify-content-end align-items-center">
            <%= f.label :isActive, "Active" %><br />
          </div>
          <div class="col-5 d-flex flex-row justify-content-start ">
            <%= f.check_box :isActive,  class: "form-check-input " %>
          </div>
        </div>
        <div class="row m-0 mt-2 ">
          <div class="col-5 d-flex flex-row justify-content-end align-items-center">
          </div>
          <div class="col-5 d-flex flex-row justify-content-start">
            <%= f.submit "Save", class: "btn save-btn mt-2", style: "color: white" %>
          </div>
        </div>
      <% end %>
    </div>
  <div class="col-0 col-lg-2"></div>
</div>
<script>
  let photoInput = document.getElementById('photoInput');
  let avtImg = document.querySelectorAll('.avt-edit-box img');
  photoInput.addEventListener('change', function(event) {
    console.log("change")
    var file = event.target.files[0];
    if (file) {
      var reader = new FileReader();
      reader.onload = function(e) {
          avtImg[0].src = e.target.result;
      };
      reader.readAsDataURL(file);
    }
  });
</script>

app/views/admins/manage_albums.html.erb
<%session[:failure_redirect]=manage_albums_path%>
<div class="row admin-album-list">

<% if flash[:notice] %>                           
    <div aria-live="polite" aria-atomic="true" class="col-12 bg-dark position-relative bd-example-toasts">
        <div class="toast-container position-absolute top-0 end-0" id="toastPlacement" style="<%=(flash[:type]=='success')? 'background-color:green': 'background-color:red'%>">
            <div class="show" >
                <div class="my-toast">
                    <%= flash[:notice] %>
                </div>
            </div>
        </div>
    </div>
<% end %>    
                <div class="col-0 col-lg-2 d-none d-lg-flex flex-row justify-content-center mt-4">
                    <ul class="d-inline-block nav-list" >
                        <a href=<%=manage_photos_path%>>
                            <li class="d-block mb-2">Manage Photos</li>
                        </a>
                        <a href="">
                            <li class="d-block mb-2">Manage Albums</li>
                        </a>
                        <a href=<%=manage_users_path%>>
                            <li class="d-block mb-2">Manage Users</li>
                        </a>
                    </ul>
                </div>
                <div class="col-12 col-lg-8 center-container d-flex flex-column align-items-center"> 
                    <div class="d-flex flex-row flex-wrap m-0 gap-2 img-container w-100" > 
                        <% @resources.find_each do |ele| %>
                            <%= render 'album_card', ele: ele %>
                        <% end %>
                    </div>
                    <div class=" w-100 d-flex justify-content-center mt-4">
                        <%== pagy_bootstrap_nav(@pagy)%>
                        
                    </div>



                    
                </div>
                <div class="col-0 col-lg-2"></div>
</div> 
<script>
function disappearToast(){
        setTimeout(function(){
            $('#toastPlacement').fadeOut();
        }, 3000);
    }
    <% if flash[:notice] %>
        disappearToast();
    <% end %>
</script>

app/views/admins/manage_photos.html.erb
<%session[:failure_redirect]=manage_photos_path%>
<div class="row admin-photo-list">

<% if flash[:notice] %>                           
    <div aria-live="polite" aria-atomic="true" class="col-12 bg-dark position-relative bd-example-toasts">
        <div class="toast-container position-absolute top-0 end-0" id="toastPlacement" style=<%=(flash[:type]=='success')? 'background-color:green': 'background-color:red'%>>
            <div class="show" >
                <div class="my-toast">
                    <%= flash[:notice] %>
                </div>
            </div>
        </div>
    </div>
<% end %>    
                <div class="col-0 col-lg-2 d-none d-lg-flex flex-row justify-content-center mt-4">
                    <ul class="d-inline-block nav-list" >
                        <a href="">
                            <li class="d-block mb-2">Manage Photos</li>
                        </a>
                        <a href=<%=manage_albums_path%>>
                            <li class="d-block mb-2">Manage Albums</li>
                        </a>
                        <a href=<%=manage_users_path%>>
                            <li class="d-block mb-2">Manage Users</li>
                        </a>
                    </ul>
                </div>
                <div class="col-12 col-lg-8 center-container d-flex flex-column align-items-center"> 
                    <div class="d-flex flex-row flex-wrap m-0 gap-4 img-container w-100" > 
                        <% @resources.find_each do |ele| %>
                            <%= render 'photo_card', ele: ele %>
                        <% end %>
                    </div>
                    <div class=" w-100 d-flex justify-content-center mt-4">
                        <%== pagy_bootstrap_nav(@pagy)  %>
                    </div>



                    
                </div>
                <div class="col-0 col-lg-2"></div>
</div> 

<script>
function disappearToast(){
        setTimeout(function(){
            $('#toastPlacement').fadeOut();
        }, 3000);
    }
    <% if flash[:notice] %>
        disappearToast();
    <% end %>
</script>

app/views/admins/manage_users.html.erb
<%session[:failure_redirect]=manage_users_path%>
<div class="row admin-user-list">

<% if flash[:notice] %>                           
    <div aria-live="polite" aria-atomic="true" class="col-12 bg-dark position-relative bd-example-toasts">
        <div class="toast-container position-absolute top-0 end-0" id="toastPlacement" style="<%=(flash[:type]=='success')? 'background-color:green': 'background-color:red' %>">
            
            <div class="show" >
                <div class="my-toast">
                    <%= flash[:notice] %>
                </div>
            </div>
        </div>
    </div>
<% end %> 
    <div class="col-0 col-lg-2 d-none d-lg-flex flex-row justify-content-center mt-4">
        <ul class="d-inline-block nav-list" >
            <a href=<%=manage_photos_path%>>
                <li class="d-block mb-2">Manage Photos</li>
            </a>
            <a href=<%=manage_users_path%>>
                <li class="d-block mb-2">Manage Albums</li>
            </a>
            <a href="">
                <li class="d-block mb-2">Manage Users</li>
            </a>
        </ul>
    </div>
    <div class="col-12 col-lg-8 center-container d-flex flex-column align-items-center"> 
        <table class="table table-borderless">
        <thead class="header-user-table">
        <tr>
            <th scope="col" >First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Last Login</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
            <% @resources.find_each do |ele| %>
                <tr>
                    <th scope="row"><%=ele.firstName%></th>
                    <td><%=ele.lastName%></td>
                    <td><%=ele.email%></td>
                    <td>
                        <% if ele.last_sign_in_at %>
                            <%=ele.last_sign_in_at.strftime("%I:%M%p %d/%m/%Y").downcase%>
                        <% else %>
                            Have not signed in
                        <% end %>
                    </td>
                    <td>
                        <%= link_to admin_edit_user_path(ele), method: :get, class: "btn save-btn" do %>
                            Edit
                        <% end %>
                        <%= link_to "/users/#{ele.id}", class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } do %>
                            Delete
                        <% end %>
                        
                    </td>
                </tr>
            <% end %>
        
        </tbody>
    </table>
    <div class=" w-100 d-flex justify-content-center mt-4">
                        <%== pagy_bootstrap_nav(@pagy)%>
                        
                    </div>
    </div>
    <div class="col-0 col-lg-2"></div>
</div>
<script>
    function disappearToast(){
        setTimeout(function(){
            $('#toastPlacement').fadeOut();
        }, 3000);
    }
    <% if flash[:notice] %>
        disappearToast();
    <% end %>
</script>
<div class="row admin-photo-list">