config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check
  root "photos#feed"
  # get "/authenticate/login", to: "authentication#login"
  # get "/authenticate/signup", to: "authentication#signup"
  # get "/feed/album", to: "feed#album"
  # get "/discover/photo", to: "discover#photo"
  # get "/discover/album", to: "discover#album"
  # get "/articles", to: "articles#index"
  # put "/discover/follow", to: "discover#follow", as: :follow
  # get "/personal_info/photo/:id", to: "personal_info#photo", as: :personal_info_photo
  # get "/personal_info/album/:id", to: "personal_info#album", as: :personal_info_album
  # get "/personal_info/following/:id", to: "personal_info#following", as: :personal_info_following
  # get "/personal_info/follower/:id", to: "personal_info#follower", as: :personal_info_follower
  # get "/users/edit/:id", to: "users#edit", as: :edit_user
  #patch "/users/update/:id", to: "users#update", as: :update_user
  devise_scope :user do
    put "/users/update/:id", to: "devise/registrations#update_name", as: :update_user
  end
  # get "/users", to: "users#index", as: :users
  # delete "/users/delete/:user_id", to: "users#destroy", as: :delete_user
  # # post "/react_photo", to: "react_photos#create"
  # # delete "/react_photo", to: "react_photos#destroy"
  # # post "/react_album", to: "react_albums#create"
  # # delete "/react_album", to: "react_albums#destroy"
  # put "/react_photos", to: "react_photos#handle_like", as: :react_photo
  # put "/react_albums", to: "react_albums#handle_like", as: :react_album
  # scope module: 'users' do
  #   resources :photos, :albums
  # end

  
  # scope module: 'users' do
  #   resources :photos, :albums
  # end
  resources :users
  get "/users/:user_id/followings", to: "follows#followings", as: :followings
  get "/users/:user_id/followers", to: "follows#followers", as: :followers
  post "/follow", to: "follows#create", as: :follow_user
  delete "/unfollow", to: "follows#destroy", as: :unfollow_user
  get "/photos/discover", to: "photos#discover", as: :discover_photo
  get "/photos/feed", to: "photos#feed", as: :feed_photo
  get "/albums/discover", to: "albums#discover", as: :discover_album
  get "/albums/feed", to: "albums#feed", as: :feed_album
  get "/follow_button/user/:user_id", to: "follows#follow_button", as: :follow_button
  get "/unfollow_button/user/:user_id", to: "follows#unfollow_button", as: :unfollow_button

  post "/react_photos", to: "react_photos#create", as: :react_photo
  delete "/unreact_photos", to: "react_photos#destroy", as: :unreact_photo
  get "/react_photo_button/photo/:photo_id", to: "react_photos#react_button", as: :react_photo_button
  get "/unreact_photo_button/photo/:photo_id", to: "react_photos#unreact_button", as: :unreact_photo_button

  post "/react_albums", to: "react_albums#create", as: :react_album
  delete "/unreact_albums", to: "react_albums#destroy", as: :unreact_album
  get "/react_album_button/album/:album_id", to: "react_albums#react_button", as: :react_album_button
  get "/unreact_album_button/album/:album_id", to: "react_albums#unreact_button", as: :unreact_album_button

 
  

  # refactoring code
  resources :users, shallow: true do
    resources :photos, :albums
  end

  # routes for admin
  get "/admin/manage_users", to: "admins#manage_users", as: :manage_users
  get "/admin/manage_photos", to: "admins#manage_photos", as: :manage_photos
  get "/admin/manage_albums", to: "admins#manage_albums", as: :manage_albums
  get "/admin/edit_user/:id", to: "admins#edit_user", as: :admin_edit_user
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
require 'carrierwave/orm/activerecord'
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :omniauthable, omniauth_providers: %i[facebook]                     
    ## uploader with carrierwave into profileImg
    mount_uploader :profileImg, ProfileImgUploader
    
    #ASSOCIATION
    has_many :albums, dependent: :destroy
    has_many :photos, dependent: :destroy
    has_many :active_relate, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
    has_many :passive_relate, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
    has_many :following, through: "active_relate", source: "followed"
    has_many :follower, through: "passive_relate", source: "follower"
    has_many :react_albums, dependent: :destroy
    has_many :reacted_albums, through: :react_albums, source: :album
    has_many :react_photos, dependent: :destroy
    has_many :reacted_photos, through: :react_photos, source: :photo
    #VALIDATION
    #validates :email, format: {with: /^[A_Za_z]+[A_Za_z0_9]*@[A_Za_z]+(.[A_Za_z]+)+$/}
    validates :email, format: {with: /\A[A-Za-z]+[A-Za-z0-9]*@[A-Za-z]+(.[A-Za-z]+)+\z/, message: "Your email format is invalid."}, length: {maximum: 255, message: "Must be 255 characters or less."}
    #validates :password,format: {with: /\A(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\W)(?!.* ).{,64}\z/, message: "must contain one digit, one lowercase letter, one uppercase letter, one special character, maximum 64 characters"}
    validates :firstName, :lastName, presence: true, length: {maximum: 25}
    validates :isActive, :isAdmin, inclusion: {in: [true, false]}
    validates_confirmation_of :password
    #validates_associated :photos, :albums
    
    #CALLBACK EVENTS
    before_validation :handle_before_validation

    #IMPLEMENT CALLBACK FUNCTIONS
    def handle_before_validation
        self.isActive = true
        self.isAdmin = false
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :just_allow_user
    before_action :handle_before_action
    def show
        @viewing_current_user = @user.id == current_user.id
        @resources = @user.photos 
        @resources = @resources.is_public if !@viewing_current_user
    end
    def index
    end
    private
        def user_params
            params.require(:user).permit(:firstName, :lastName, :email)
        end
        def handle_before_action
            @user = User.find(params[:id])
            @list_followings = current_user.following.pluck(:id)
        end
end

app/helpers/users/albums_helper.rb
module Users::AlbumsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/photos_helper.rb
module Users::PhotosHelper
end

app/views/users/show.html.erb
<%session[:failure_redirect]=user_path(current_user)%>
<div class="row personal-info photo">
        <div class="col-0 col-lg-2 d-none d-lg-flex flex-row justify-content-center mt-4">
                    <ul class="d-inline-block nav-list album-nav" >
                        <a href="/">
                            <li class="d-block mb-2">Feeds</li>
                        </a>
                        <a href="/discover/photo">
                            <li class="d-block mb-2">Discover</li>
                        </a>
                    </ul>
        </div>
    <div class="col-12 col-lg-8 center-container d-flex flex-column align-items-center"> 
        <div class="row w-100 ">
            <div class="col-3 p-0">
                <div class="user-avt-box">
                    <%if @user.profileImg.identifier%>
                        <%if %w(http https).include?(URI.parse(@user.profileImg.identifier).scheme)%>
                            <img src="<%=@user.profileImg.identifier%>" alt="">
                        <%else%>
                            <img src="<%=@user.profileImg%>" alt="">
                        <%end%>
                        
                    <%else%>
                        <img src="" alt="">
                    <%end%>
                </div>
            </div>
            <div class="col-9 d-flex flex-column gap-10">
                <% if @viewing_current_user %>
                    <div>
                        <%= link_to edit_user_registration_path, class:"edit-profile-btn" do %>
                            <button>Edit Profile</button>
                        <% end %>
                    </div>
                <% else %>
                    <div class="follow-container">
                        <%if @list_followings.include?@user.id%>
                            <%=render 'shared/unfollow_button', id:@user.id%>
                        <%else%>
                            <%= render 'shared/follow_button', id: @user.id %>
                        <%end%>
                    </div>
                <% end %>
                <h2><%=@user.firstName + " " + @user.lastName%></h2>
                <div >
                    <ul class="personal_nav p-0 m-0">
                        <%= link_to user_photos_path(@user), remote: true do%>
                            <li id="photos-personal-nav"><span><%=@user.photos.size%></span> PHOTOS</li>
                        <% end %>
                        <%= link_to user_albums_path(@user) , remote: true do %>
                            <li id="albums-personal-nav"><span><%=@user.albums.size%></span> ALBUMS</li>
                        <% end %>
                        <%= link_to followings_path(@user) , remote: true do %>
                            <li id="followings-personal-nav"><span><%=@user.following.size%></span> FOLLOWINGS</li>
                        <% end %>
                        <%= link_to followers_path(@user) , remote: true do %>
                            <li id="followers-personal-nav"><span><%=@user.follower.size%></span> FOLLOWERS</li>
                        <% end %>
            
                    </ul>
                </div>
            </div>
        </div>
        <% if @viewing_current_user %>
            <div class="add-button d-flex flex-row justify-content-end w-100 gap-40 m-0 mt-5">
                    <%= render '/photos/add_photo_button' %>
            </div>
        <% end %>                    
        <div class="resource-container row gap-20 m-0 mt-5 w-100">
            <%= render 'photos/list_photos', resources: @resources%>
        </div>
    </div>
    <div class="col-0 col-lg-2"></div>
    
</div>
<script>
function followAPI(id){
    $.ajax({
    url: "/follow",
    type: "POST",
    dataType: "html",
    data: {user_id: id},
    success: function(data) {
        console.log('follow success')
        console.log(data)
        fetchUnfollowButtonHTML(id)
        
        let unfollowBtns =  document.querySelectorAll('.unfollow-btn-'+id)  
        unfollowBtns.forEach((btn)=>{
            btn.addEventListener('click',function stopPropagation(event){
                debounceFollow(unfollowAPI)(btn.querySelector('p').innerHTML)
            })
    })
    },
    error: function(data) {
        console.log('follow error')
        console.log(data.status)
        
    }
    })
}
function fetchUnfollowButtonHTML(id){
    $.ajax({
        url: `/unfollow_button/user/${id}`,
        type: "GET",
        dataType: "html",
        data: {user_id: id},
        success: function(html) {
            console.log('fetch unfollow button success')
           
            $(`.follow-btn-${id}`).parent().html(html);
        },
        error: function(data) {
            console.log('fetch unfollow button error')
            console.log(data.status)
            
        }
    })

}
function unfollowAPI(id){
    $.ajax({
    url: "/unfollow",
    type: "DELETE",
    dataType: "html",
    data: {user_id: id},
    success: function(data) {
        console.log('unfollow success')
        console.log(data)
        fetchFollowButtonHTML(id)
        let followBtns =   document.querySelectorAll('.follow-btn-<%=@user.id.to_s%>')  
        followBtns.forEach((btn)=>{
            btn.addEventListener('click',function stopPropagation(event){
                debounceFollow(followAPI)(btn.querySelector('p').innerHTML)
            })
        }) 
    },
    error: function(data) {
        console.log('unfollow error')
        console.log(data.status)
        
    }
})
function fetchFollowButtonHTML(id){
    $.ajax({
        url: `/follow_button/user/${id}`,
        type: "GET",
        dataType: "html",
        data: {user_id: id},
        success: function(html) {
            console.log('fetch unfollow button success')
            
            $(`.unfollow-btn-${id}`).parent().html(html);
        },
        error: function(data) {
            console.log('fetch unfollow button error')
            console.log(data.status)
            
        }
    })

}
}
    const debounceFollow= function (func, timeout = 3000){
    return (...args) => {
        console.log(this.timer)
        clearTimeout(this.timer);
        this.timer = setTimeout(() => { func.apply(this, args); }, timeout);
    };
}  
</script>
<%#<%= javascript_pack_tag 'add_event_follow_button'%>