config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check
  root "photos#feed"
  # get "/authenticate/login", to: "authentication#login"
  # get "/authenticate/signup", to: "authentication#signup"
  # get "/feed/album", to: "feed#album"
  # get "/discover/photo", to: "discover#photo"
  # get "/discover/album", to: "discover#album"
  # get "/articles", to: "articles#index"
  # put "/discover/follow", to: "discover#follow", as: :follow
  # get "/personal_info/photo/:id", to: "personal_info#photo", as: :personal_info_photo
  # get "/personal_info/album/:id", to: "personal_info#album", as: :personal_info_album
  # get "/personal_info/following/:id", to: "personal_info#following", as: :personal_info_following
  # get "/personal_info/follower/:id", to: "personal_info#follower", as: :personal_info_follower
  # get "/users/edit/:id", to: "users#edit", as: :edit_user
  #patch "/users/update/:id", to: "users#update", as: :update_user
  devise_scope :user do
    put "/users/update/:id", to: "devise/registrations#update_name", as: :update_user
  end
  # get "/users", to: "users#index", as: :users
  # delete "/users/delete/:user_id", to: "users#destroy", as: :delete_user
  # # post "/react_photo", to: "react_photos#create"
  # # delete "/react_photo", to: "react_photos#destroy"
  # # post "/react_album", to: "react_albums#create"
  # # delete "/react_album", to: "react_albums#destroy"
  # put "/react_photos", to: "react_photos#handle_like", as: :react_photo
  # put "/react_albums", to: "react_albums#handle_like", as: :react_album
  # scope module: 'users' do
  #   resources :photos, :albums
  # end

  
  # scope module: 'users' do
  #   resources :photos, :albums
  # end
  resources :users
  get "/users/:user_id/followings", to: "follows#followings", as: :followings
  get "/users/:user_id/followers", to: "follows#followers", as: :followers
  post "/follow", to: "follows#create", as: :follow_user
  delete "/unfollow", to: "follows#destroy", as: :unfollow_user
  get "/photos/discover", to: "photos#discover", as: :discover_photo
  get "/photos/feed", to: "photos#feed", as: :feed_photo
  get "/albums/discover", to: "albums#discover", as: :discover_album
  get "/albums/feed", to: "albums#feed", as: :feed_album
  get "/follow_button/user/:user_id", to: "follows#follow_button", as: :follow_button
  get "/unfollow_button/user/:user_id", to: "follows#unfollow_button", as: :unfollow_button

  post "/react_photos", to: "react_photos#create", as: :react_photo
  delete "/unreact_photos", to: "react_photos#destroy", as: :unreact_photo
  get "/react_photo_button/photo/:photo_id", to: "react_photos#react_button", as: :react_photo_button
  get "/unreact_photo_button/photo/:photo_id", to: "react_photos#unreact_button", as: :unreact_photo_button

  post "/react_albums", to: "react_albums#create", as: :react_album
  delete "/unreact_albums", to: "react_albums#destroy", as: :unreact_album
  get "/react_album_button/album/:album_id", to: "react_albums#react_button", as: :react_album_button
  get "/unreact_album_button/album/:album_id", to: "react_albums#unreact_button", as: :unreact_album_button

 
  

  # refactoring code
  resources :users, shallow: true do
    resources :photos, :albums
  end

  # routes for admin
  get "/admin/manage_users", to: "admins#manage_users", as: :manage_users
  get "/admin/manage_photos", to: "admins#manage_photos", as: :manage_photos
  get "/admin/manage_albums", to: "admins#manage_albums", as: :manage_albums
  get "/admin/edit_user/:id", to: "admins#edit_user", as: :admin_edit_user
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/photo.rb
require 'carrierwave/orm/activerecord'
class Photo < ApplicationRecord
    mount_uploader :image, PhotoUploader
    #ASSOCIATION
    belongs_to :user
    belongs_to :album, optional: true
    has_many :react_photos, dependent: :destroy
    has_many :reacting_users, through: :react_photos, source: :user
    #VALIDATION
    validates :title, length: {maximum: 140, message: "Must be 140 characters or less"}
    validates :description, length: {maximum: 300, message: "Must be 300 characters or less"}
    validates :isPrivate, inclusion: {in: [true, false]}
    #validates :image, presence: true
    validates :numOfLikes, numericality: { only_integer: true , message: "Must be an integer"}
    #SCOPES
    scope :is_public, -> { where(isPrivate: false) }
    scope :is_private, -> { where(isPrivate: true) }
    #CALLBACK EVENTS
    before_validation :handle_before_validation
    before_destroy :handle_before_destroy
    before_create :handle_before_create
    def handle_before_validation
        self.numOfLikes=0 if self.numOfLikes == nil
        self.isPrivate=true if isPrivate == nil
    end
    def handle_before_destroy
        self.album.update(numOfPhotos: self.album.numOfPhotos - 1) if self.album_id != nil
    end
    def handle_before_create
        self.album.update(numOfPhotos: self.album.numOfPhotos + 1) if self.album_id != nil
    end
    
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    Pagy::DEFAULT[:limit] = 10
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :index]
    before_action :just_allow_user, only: [:new, :create, :feed,:discover, :index]
    before_action :before_action_handle1, only: [:feed, :discover]
    before_action :get_resource, only: [:edit, :update, :destroy]
    before_action :get_user, only: [:index, :new]
    def discover
        #@pagy,@resources = pagy(Photo.is_public.includes(:user))
        @resources = Photo.is_public.includes(:user).paginate(page: params[:page], per_page: 10)
    end
    def feed
        @resources = []
        if user_signed_in?
            #@pagy,@resources = pagy(Photo.where(user_id: @list_followings).where(isPrivate: false).includes(:user).order('created_at DESC'))
            @resources = Photo.where(user_id: @list_followings).where(isPrivate: false).includes(:user).order('created_at DESC').paginate(page: params[:page], per_page: 4)
        end
    end
    def index
        @viewing_current_user = @user.id == current_user.id
        @resources = @user.photos
        @resources = @resources.is_public if !@viewing_current_user
    end
    def new
        @resource = Photo.new
    end
    def create
        new_photo_params = photo_params.dup
        new_photo_params[:isPrivate] = new_photo_params[:isPrivate] == "1"
        resource = current_user.photos.new(new_photo_params)
        if resource.save
            set_my_flash_message("Photo was successfully created.", "success")
            redirect_to session[:success_redirect] || root_path
        else
            set_my_flash_message("Photo was not created.", "error")
            render :new
        end
    end
    def edit
    end
    def update
        if @resource.update(photo_params)
            set_my_flash_message("Photo was successfully updated.", "success")
            
            redirect_to session[:success_redirect] || root_path
        else 
            set_my_flash_message("Photo was not updated.", "error")
            render :edit
        end
    end
    def destroy
        if @resource.destroy
            set_my_flash_message("Photo was successfully deleted.", "success")
            redirect_to session[:success_redirect] || root_path
        else
            set_my_flash_message("Photo was not deleted.", "error")
            render :edit
        end
    end
    private
    def before_action_handle1
        @list_reacted_photos = []
        @list_reacted_photos = current_user.reacted_photos.pluck(:id) if user_signed_in?
        @list_followings = []
        @list_followings = current_user.following.pluck(:id) if user_signed_in?
    end
    def get_resource
        @resource = Photo.find params[:id]
    end
    def get_user
        @user = User.find params[:user_id]
    end
    def photo_params
        params.require(:photo).permit(:title, :description, :isPrivate, :image)
    end
    
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users/photos_helper.rb
module Users::PhotosHelper
end

app/views/photos/_add_photo_button.html.erb
<%= link_to new_user_photo_path(current_user) do %>
    <button class="btn  add-btn">Add Photo</button>
<% end %>

app/views/photos/_list_discover_photos.html.erb
<%resources = local_assigns[:resources]%>
<% if resources.empty? %>
    <div class="col-12 d-flex justify-content-center align-items-center mb-4 mt-4">
        <p>There is no photo</p>
    </div>
<% else %>
    <div id="photos" class="w-100 row">
        <%= turbo_frame_tag "photos", src: discover_photo_path(format: :turbo_stream), loading: :lazy %>
    </div>
    <% if user_signed_in? %>
        <% if @resources.next_page %>
            <%= turbo_frame_tag "load_more", src: discover_photo_path(page:  @resources.next_page, format: :turbo_stream), loading: :lazy %>
        <% end %>
    <% end %>
    
<% end %>

app/views/photos/_list_feed_photos.html.erb
<%resources = local_assigns[:resources]%>
<% if !user_signed_in? %>
    <div class="col-12 d-flex justify-content-center align-items-center ">
        <p> Please sign in to view this content</p>
    </div>
<% elsif @list_followings.empty? %>
    <div class="col-12 d-flex justify-content-center align-items-center">
        <p>Please follow some friends to have content in this page</p>
    </div>
<% else %> 
    
    <div id="photos" class="w-100 row">
        <%= turbo_frame_tag "photos", src: feed_photo_path(format: :turbo_stream), loading: :lazy %>
    </div>
    <% if user_signed_in? %>
        <% if @resources.next_page %>
            <%= turbo_frame_tag "load_more", src: feed_photo_path(page:  @resources.next_page, format: :turbo_stream), loading: :lazy %>
        <% end %>
    <% end %>
<% end %>

app/views/photos/_photo_card.html.erb
<% ele = local_assigns[:ele] %>
<div class="col-2 d-flex flex-column img-box g-1">
    <%= render '/shared/display_image', ele: ele.image%>
    
    
    <% if ele.title %>
        <p class="mt-2"><%=ele.title%></p>
    <% else %>
        <p class="mt-2">no title</p>
    <% end %>
    <% if ele.isPrivate %>
        <div class="private-box">
            <i class="fa-solid fa-lock"></i>
        </div>
    <% end %>
    <% if @viewing_current_user %>
        <%= button_to edit_photo_path(ele), method: :get, class: 'edit-btn' do %>
            EDIT
        <% end %>
    <% end %>
</div>  

app/views/photos/discover.html.erb
<%session[:failure_redirect]=discover_photo_path%>
<div class="row discover photo">
    <div class="col-0 col-lg-2 d-flex flex-row justify-content-center mt-4">
        <ul class="d-none d-lg-inline-block nav-list" >
            <a href="/photos/feed">
                <li class="d-block mb-2">Feeds</li>
            </a>
            <a href="#">
                <li class="d-block mb-2">Discover</li>
            </a>
        </ul>
    </div>
    <div class="col-12 col-lg-8 center-container d-flex flex-column align-items-center"> 
        
        <div class="switch-mode d-flex mt-4">
            <%= link_to discover_photo_path, remote: true do%>
                <div class="photo-btn p-2">PHOTO</div>
            <%end%>
            <%=link_to discover_album_path, remote: true do%>
                <div class="album-btn p-2">ALBUM</div>
            <%end%>
        </div>
        <div class="row w-100 mt-4 mb-4 resources-container " >
            <%= render 'list_discover_photos', resources: @resources%>
        </div>
        
    </div>                   
</div>
<script>
    function followAPI(id){
    $.ajax({
    url: "/follow",
    type: "POST",
    dataType: "html",
    data: {user_id: id},
    success: function(data) {
        console.log('follow success')
        console.log(data)
        fetchUnfollowButtonHTML(id)
        

    }
    ,
    error: function(data) {
        console.log('follow error')
        console.log(data.status)
        
    }
    })
}
function fetchUnfollowButtonHTML(id){
    $.ajax({
        url: `/unfollow_button/user/${id}`,
        type: "GET",
        dataType: "html",
        data: {user_id: id},
        success: function(html) {
            console.log('fetch unfollow button success')
           
            $(`.follow-btn-${id}`).parent().html(html);
        },
        error: function(data) {
            console.log('fetch unfollow button error')
            console.log(data.status)
            
        }
    })

}
function unfollowAPI(id){
    $.ajax({
    url: "/unfollow",
    type: "DELETE",
    dataType: "html",
    data: {user_id: id},
    success: function(data) {
        console.log('unfollow success')
        console.log(data)
        fetchFollowButtonHTML(id)
    },
    error: function(data) {
        console.log('unfollow error')
        console.log(data.status)
        
    }
})
function fetchFollowButtonHTML(id){
    $.ajax({
        url: `/follow_button/user/${id}`,
        type: "GET",
        dataType: "html",
        data: {user_id: id},
        success: function(html) {
            console.log('fetch unfollow button success')
            
            $(`.unfollow-btn-${id}`).parent().html(html);
        },
        error: function(data) {
            console.log('fetch unfollow button error')
            console.log(data.status)
            
        }
    })

}
}
const debounceFollow= function (func, timeout = 3000){
return (...args) => {
    console.log(this.timer)
    clearTimeout(this.timer);
    this.timer = setTimeout(() => { func.apply(this, args); }, timeout);
};
} 

function reactPhotoApi(id){
    $.ajax({
        url: "/react_photos",
        type: "POST",
        data: {photo_id: id},
        success: function(data) {
            fetchUnreactPhotoButton(id)
        },
        error: function(data) {}
    })
}
function fetchUnreactPhotoButton(id){
$.ajax({
    url: `/unreact_photo_button/photo/${id}`,
    type: "GET",
    dataType: "html",
    data: {photo_id: id},
    success: function(html) {
        console.log('fetch unreact button success')
        $(`.react-photo-btn-${id}`).parent().html(html);
    },
    error: function(data) {
        console.log('fetch unfollow button error')
        console.log(data.status)
        
    }
})
}
function unreactPhotoApi(id){
    $.ajax({
        url: "/unreact_photos",
        type: "DELETE",
        data: {photo_id: id},
        success: function(data) {
            fetchReactPhotoButton(id)
        },
        error: function(data) {}
    })
}
function fetchReactPhotoButton(id){
$.ajax({
    url: `/react_photo_button/photo/${id}`,
    type: "GET",
    dataType: "html",
    data: {photo_id: id},
    success: function(html) {
        console.log('fetch unreact button success')
        $(`.unreact-photo-btn-${id}`).parent().html(html);
    },
    error: function(data) {
        console.log('fetch unfollow button error')
        console.log(data.status)
        
    }
})
}


function reactAlbumApi(id){
    $.ajax({
        url: "/react_albums",
        type: "POST",
        data: {album_id: id},
        success: function(data) {
            fetchUnreactAlbumButton(id)
        },
        error: function(data) {}
    })
}
function fetchUnreactAlbumButton(id){
$.ajax({
    url: `/unreact_album_button/album/${id}`,
    type: "GET",
    dataType: "html",
    data: {album_id: id},
    success: function(html) {
        console.log('fetch unreact button success')
        $(`.react-album-btn-${id}`).parent().html(html);
    },
    error: function(data) {
        console.log('fetch unfollow button error')
        console.log(data.status)
        
    }
})
}
function unreactAlbumApi(id){
    $.ajax({
        url: "/unreact_albums",
        type: "DELETE",
        data: {album_id: id},
        success: function(data) {
            fetchReactAlbumButton(id)
        },
        error: function(data) {}
    })
}
function fetchReactAlbumButton(id){
$.ajax({
    url: `/react_album_button/album/${id}`,
    type: "GET",
    dataType: "html",
    data: {album_id: id},
    success: function(html) {
        console.log('fetch unreact button success')
        $(`.unreact-album-btn-${id}`).parent().html(html);
    },
    error: function(data) {
        console.log('fetch unfollow button error')
        console.log(data.status)
        
    }
})
}


const debounceReact = function (func, timeout = 3000){
return (...args) => {
    console.log(this.timer)
    clearTimeout(this.timer);
    this.timer = setTimeout(() => { func.apply(this, args); }, timeout);
};
}

function showModal(modalId){
var myModal = new bootstrap.Modal(document.getElementById(modalId), {
    keyboard: false
})
myModal.show()
}
</script>
<%#<%= javascript_pack_tag 'add_event_follow_button'%>

app/views/photos/discover.js.erb
$(".resources-container").html("<%= escape_javascript(render 'list_discover_photos', resources: @resources) %>")
$(".switch-mode .album-btn").css({"color": "var(--main-color)", "background-color": "white"})
$(".switch-mode .photo-btn").css({"color": "white", "background-color": "var(--main-color)"})

app/views/photos/edit.html.erb
<%session[:success_redirect]=user_path(current_user)%>
<div class="row new-photo">

<% if flash[:notice] %>                           
    <div aria-live="polite" aria-atomic="true" class="col-12 bg-dark position-relative bd-example-toasts">
        <div class="toast-container position-absolute top-0 end-0" id="toastPlacement" style="<%=(flash[:type]=='success')? 'background-color:green': 'background-color:red'%>">
            <div class="show" >
                <div class="my-toast">
                    <%= flash[:notice] %>
                </div>
            </div>
        </div>
    </div>
<% end %>    
                <div class="col-0 col-lg-2 d-none d-lg-flex flex-row justify-content-center mt-4">
                    <ul class="d-inline-block nav-list" >
                        <a href="#">
                            <li class="d-block mb-2">Feeds</li>
                        </a>
                        <a href="/discover/photo">
                            <li class="d-block mb-2">Discover</li>
                        </a>
                    </ul>
                </div>
                <div class="col-12 col-lg-8 center-container d-flex flex-column align-items-center"> 
                    <div class="header w-100 d-flex flex-row justify-content-start">
                        <p>Edit photo</p>
                    </div>
                    
                    <%= form_with(model: @resource,url: "/photos/#{@resource.id}" ,class: "w-100 mt-4" ) do |f| %>
                        
                        <div class="row w-100">
                            <div class= "col-6 d-flex flex-column gap-20">
                                <div>
                                    <%= f.label :title , class: "form-label"%>
                                    <%= f.text_field :title, class: "form-control", placeholder: "Photo title" %>
                                    <% if @resource.errors.has_key?(:title) %>
                                        <p class="error-message mb-0"> <%= @resource.errors[:title].first %></p>
                                    <% end %>
                                </div>
                                <div>
                                    <%= f.label :isPrivate, "Sharing mode" , class: "form-label"%>
                                    <br/>
                                    <div class="sharing-mode-box">
                                        <%= f.select :isPrivate,  options_for_select([["Public", "0"], ["Private", "1"]], selected: (f.object.isPrivate)? "1" : "0" ) , {},{class: 'sharing-mode'}%>
                                        <i class="fa-solid fa-angle-down down-arrow"></i>
                                    </div>
                                    
                                </div>
                                <div class="upload-photo-box mt-3">
                                    <%= f.file_field :image, class: "form-control browse-btn", id: "photoInput" %>
                                    
                                    <i class="fa-solid fa-plus add-btn"></i>
                                    <div id="previewImage" >
                                        <%= render '/shared/display_image', ele: f.object.image%>
                                        
                                        <i class="fa-solid fa-xmark close-img-btn"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <%= f.label :description, class: "form-label" %>
                                <%= f.text_area :description, class: "form-control h-50" , placeholder: "Photo Description"%>
                                <% if @resource.errors.has_key?(:description) %>
                                    <p class="error-message mb-0"> <%= @resource.errors[:description].first %></p>
                                <% end %>
                            </div>
                        </div>
                        
                        <div>
                            <%= f.submit "Save", class: "btn btn-primary save-btn mt-4" %>
                            <%= link_to "Delete", @resource, class: "btn btn-danger delete-btn mt-4" , method: :delete%>
                        </div>
                    <% end %>

                    
                </div>
                <div class="col-0 col-lg-2"></div>
</div> 

<script>
    function disappearToast(){
        setTimeout(function(){
            $('#toastPlacement').fadeOut();
        }, 3000);
    }
    <% if flash[:notice] %>
        disappearToast();
    <% end %>
                   

    var photoInput = document.getElementById('photoInput');
    var previewImage = document.getElementById('previewImage');
    var closeBtn = document.querySelector('.close-img-btn');
    function clearFileInput() {
        photoInput.value = ''; // This clears the selected file
        previewImage.style.display = 'none';
    }
    closeBtn.addEventListener('click', function(event) {
        clearFileInput();
        event.stopPropagation();
    });
    
    photoInput.addEventListener('change', function(event) {
        console.log("change")
        var file = event.target.files[0];
        if (file) {
        var reader = new FileReader();
        reader.onload = function(e) {
            previewImage.querySelector('img').src = e.target.result;
            previewImage.style.display = 'block';
        };
        reader.readAsDataURL(file);
        }
    });
</script>

app/views/photos/feed.html.erb
<%session[:failure_redirect]=root_path%>
<!DOCTYPE html>
<html>
  <head>
    <title>RubyPj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    
  </head>
    <body>
    <div class="row feed photo">
        <div class="col-0 col-lg-2 d-none d-lg-flex flex-row justify-content-center mt-4">
            <ul class="d-inline-block nav-list album-nav" >
                <a href="#">
                    <li class="d-block mb-2">Feeds</li>
                </a>
                <a href="/photos/discover">
                    <li class="d-block mb-2">Discover</li>
                </a>

                
            </ul>
        </div>
        <div class="col-12 col-lg-8 center-container d-flex flex-column align-items-center"> 
            
            <div class="switch-mode d-flex mt-4">
                <%= link_to feed_photo_path, remote: true do%>
                    <div class="photo-btn p-2">PHOTO</div>
                <%end%>
                <%= link_to feed_album_path, remote: true do%>
                
                    <div class="album-btn p-2">ALBUM</div>
                <%end%>
                
            </div>
            <div class="row w-100 feed_photo mt-4 mb-4 resources-container" >
                <%=render 'list_feed_photos', resources: @resources%>
            </div> 
            
        </div>
        <div class="col-0 col-lg-2"></div>
    </div> 
    
    </body>
</html>
<script> 
console.log('Hello from photos feed')                                    
function reactPhotoApi(id){
    $.ajax({
        url: "/react_photos",
        type: "POST",
        data: {photo_id: id},
        success: function(data) {
            fetchUnreactPhotoButton(id)
        },
        error: function(data) {}
    })
}
function fetchUnreactPhotoButton(id){
$.ajax({
    url: `/unreact_photo_button/photo/${id}`,
    type: "GET",
    dataType: "html",
    data: {photo_id: id},
    success: function(html) {
        console.log('fetch unreact button success')
        $(`.react-photo-btn-${id}`).parent().html(html);
    },
    error: function(data) {
        console.log('fetch unfollow button error')
        console.log(data.status)
        
    }
})
}
function unreactPhotoApi(id){
    $.ajax({
        url: "/unreact_photos",
        type: "DELETE",
        data: {photo_id: id},
        success: function(data) {
            fetchReactPhotoButton(id)
        },
        error: function(data) {}
    })
}
function fetchReactPhotoButton(id){
$.ajax({
    url: `/react_photo_button/photo/${id}`,
    type: "GET",
    dataType: "html",
    data: {photo_id: id},
    success: function(html) {
        console.log('fetch unreact button success')
        $(`.unreact-photo-btn-${id}`).parent().html(html);
    },
    error: function(data) {
        console.log('fetch unfollow button error')
        console.log(data.status)
        
    }
})
}


function reactAlbumApi(id){
    $.ajax({
        url: "/react_albums",
        type: "POST",
        data: {album_id: id},
        success: function(data) {
            fetchUnreactAlbumButton(id)
        },
        error: function(data) {}
    })
}
function fetchUnreactAlbumButton(id){
$.ajax({
    url: `/unreact_album_button/album/${id}`,
    type: "GET",
    dataType: "html",
    data: {album_id: id},
    success: function(html) {
        console.log('fetch unreact button success')
        $(`.react-album-btn-${id}`).parent().html(html);
    },
    error: function(data) {
        console.log('fetch unfollow button error')
        console.log(data.status)
        
    }
})
}
function unreactAlbumApi(id){
    $.ajax({
        url: "/unreact_albums",
        type: "DELETE",
        data: {album_id: id},
        success: function(data) {
            fetchReactAlbumButton(id)
        },
        error: function(data) {}
    })
}
function fetchReactAlbumButton(id){
$.ajax({
    url: `/react_album_button/album/${id}`,
    type: "GET",
    dataType: "html",
    data: {album_id: id},
    success: function(html) {
        console.log('fetch unreact button success')
        $(`.unreact-album-btn-${id}`).parent().html(html);
    },
    error: function(data) {
        console.log('fetch unfollow button error')
        console.log(data.status)
        
    }
})
}


const debounceReact = function (func, timeout = 3000){
return (...args) => {
    console.log(this.timer)
    clearTimeout(this.timer);
    this.timer = setTimeout(() => { func.apply(this, args); }, timeout);
};
}
function showModal(modalId){
var myModal = new bootstrap.Modal(document.getElementById(modalId), {
    keyboard: false
})
myModal.show()
}
</script>

<%#<%= javascript_pack_tag 'photos_feed_add_event'%>

app/views/photos/new.html.erb
<div class="row new-photo">
                <div class="col-0 col-lg-2 d-none d-lg-flex flex-row justify-content-center mt-4">
                    <ul class="d-inline-block nav-list" >
                        <a href="/">
                            <li class="d-block mb-2">Feeds</li>
                        </a>
                        <a href=<%=discover_photo_path%>>
                            <li class="d-block mb-2">Discover</li>
                        </a>
                    </ul>
                </div>
                <div class="col-12 col-lg-8 center-container d-flex flex-column align-items-center"> 
                    <div class="header w-100 d-flex flex-row justify-content-start">
                        <p>New photo</p>
                    </div>
                    
                    <%= form_with model:@resource,url: "/users/#{@user.id}/photos", html: {multipart: true}, method: :post, class: "w-100 mt-4" do |f| %>
                        <div class="row w-100">
                            <div class= "col-6 d-flex flex-column gap-20">
                                <div>
                                    <%= f.label :title , class: "form-label"%>
                                    <%= f.text_field :title, class: "form-control", placeholder: "Photo title" %>
                                </div>
                                <div>
                                    <%= f.label :isPrivate, "Sharing mode" , class: "form-label"%>
                                    <br/>
                                    <div class="sharing-mode-box">
                                        <%= f.select :isPrivate,  [["Public", "0"], ["Private", "1"]] , {},{class: 'sharing-mode'}%>
                                        <i class="fa-solid fa-angle-down down-arrow"></i>
                                    </div>
                                    
                                </div>
                                <div class="upload-photo-box mt-3">
                                    <%= f.file_field :image, class: "form-control browse-btn", id: "photoInput" %>
                                    <i class="fa-solid fa-plus add-btn"></i>
                                    <div id="previewImage" style= "display: none">
                                        <img  src="#" alt="" />
    
                                            <i class="fa-solid fa-xmark close-img-btn"></i>
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <%= f.label :description, class: "form-label" %>
                                <%= f.text_area :description, class: "form-control h-50" , placeholder: "Photo Description"%>
                            </div>
                        </div>
                        
                        <%= f.submit "Save", class: "btn btn-primary save-btn mt-4" %>
                        
                    <% end %>
                        
        

                    
                </div>
                <div class="col-0 col-lg-2"></div>
            </div> 
<script>


    var photoInput = document.getElementById('photoInput');
    var previewImage = document.getElementById('previewImage');
    var closeBtn = document.querySelector('.close-img-btn');
    function clearFileInput() {
        photoInput.value = ''; // This clears the selected file
        previewImage.style.display = 'none';
    }
    closeBtn.addEventListener('click', function(event) {
        clearFileInput();
        event.stopPropagation();
    });
    
    photoInput.addEventListener('change', function(event) {
        console.log("change")
        var file = event.target.files[0];
        if (file) {
        var reader = new FileReader();
        reader.onload = function(e) {
            previewImage.querySelector('img').src = e.target.result;
            previewImage.style.display = 'block';
        };
        reader.readAsDataURL(file);
        }
    });
</script>